--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: is_valid_utf8(bytea); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.is_valid_utf8(data bytea) RETURNS boolean
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM convert_from(data, 'UTF8');
    RETURN TRUE;
EXCEPTION
    WHEN others THEN
        RETURN FALSE;
END;
$$;


ALTER FUNCTION public.is_valid_utf8(data bytea) OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    id_a integer NOT NULL,
    balance integer,
    id_c integer
);


ALTER TABLE public.account OWNER TO postgres;

--
-- Name: account_id_a_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN id_a ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_a_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer (
    id_c integer NOT NULL,
    name text,
    password text
);


ALTER TABLE public.customer OWNER TO postgres;

--
-- Name: customer_id_c_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customer ALTER COLUMN id_c ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_c_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id_a);


--
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id_c);


--
-- Name: account account_id_c_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_id_c_fkey FOREIGN KEY (id_c) REFERENCES public.customer(id_c) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

